#!/bin/bash

BAK_DIR=/mnt/Grishka/Fichiers/save/home-again

# Perform a backup if not existing yet
backup() {
	local readonly bak_ark="$BAK_DIR/ha_$(date +%Y%V).bak.tgz"
	if [ ! -f "$bak_ark" ]
	then
		tar czf "$bak_ark" rethinkdb_data/ VERSION
		echo -e "\e[32mDatabase backup created\e[0m ($bak_ark)"
	fi
}

start() {
	# We could serve it with security, but it means managing migration
	## hz serve --secure no --permissions no --port 8000
	# ... or just run it as dev
	local readonly container_name="rethink-home-prod"
	local readonly docker_port=28115
	local readonly running=$(docker ps --format "{{.Names}}" | grep $container_name)
	if [ -z "$running"]
	then
		# Test if the docker exist
		local readonly existing=$(docker ps -a --format "{{.Names}}" | grep $container_name)
		if [ -n "$existing" ]
		then
			# Restart the container
			docker start "$container_name"
		else
			docker run -d --name "$container_name" -v "$PWD:/data" -p 8180:8080 -p "$docker_port:28015" -p 29115:29015
		fi
	fi # else, the container is up and running
	local readonly docker_ip="$(docker inspect --format '{{.NetworkSettings.IPAddress}}' $container_name)"
	hz serve --dev --port 8000 --serve-static build/ --connect "$docker_ip:$docker_port"
}

backup
start