#!/bin/bash

BAK_DIR=/mnt/Grishka/Fichiers/save/home-again

# Perform a backup if not existing yet
backup() {
	local readonly bak_ark="$BAK_DIR/ha_$(date +%Y%V).bak.tgz"
	if [ ! -f "$bak_ark" ]
	then
		tar czf "$bak_ark" rethinkdb_data/ VERSION
		echo -e "\e[32mDatabase backup created\e[0m ($bak_ark)"
	fi
}

start() {
	# We could serve it with security, but it means managing migration
	## hz serve --secure no --permissions no --port 8000
	# ... or just run it as dev
	hz serve --dev --port 8000
}

backup
start