# This is a TOML document

[collections.accounts]
[[collections.accounts.indexes]]
fields = [["name"]]

[collections.messages]
[[collections.messages.indexes]]
fields = [["datetime"]]

[collections.transactions]
[[collections.transactions.indexes]]
fields = [["account"],["date"]]
[[collections.transactions.indexes]]
fields = [["date"]]
[[collections.transactions.indexes]]
fields = [["updatedAt"]]

[collections.users]

[collections.categories]
[[collections.categories.indexes]]
fields = [["name"]]

[groups.admin]
[groups.admin.rules.carte_blanche]
template = "any()"
